# Configuration de la base de données
spring:
  application:
    name: wallet-ms
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:1234/bankati}
    username: ${SPRING_DATASOURCE_USERNAME:bankati}
    password: ${SPRING_DATASOURCE_PASSWORD:bankati}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: postgresql

# Port du microservice
server:
  port: 8082

# External API Configuration
api:
  exchangerates:
    access_key: ${EXCHANGERATES_ACCESS_KEY:c7e8306539b39b00f8548283}
  coinmarketcap:
    api:
      key: ${COINMARKETCAP_API_KEY:dc2942b6-c201-42b0-8e18-24b1cc656f8e}

# Eureka Configuration
eureka:
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8081/eureka/}
